services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your React app Dockerfile
    ports:
      - "80:80"
    container_name: ruralmart-marketplace-frontend
    environment:
      - REACT_APP_API_URL=https://your-backend-render-url.com  # Pass the backend API URL as environment variable
